# Generated by Django 3.2 on 2022-05-30 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_product_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundOrdersRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField()),
                ('message', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('Confirmation', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_price', models.PositiveBigIntegerField()),
                ('product_company_price', models.BigIntegerField(default=0)),
                ('total_product_company_price', models.PositiveBigIntegerField(blank=True, null=True)),
                ('total_amount', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('order_id', models.UUIDField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('p', 'payed'), ('r', 'refund')], max_length=20)),
                ('total_price', models.BigIntegerField(blank=True, null=True)),
                ('confirmation', models.BooleanField(default=False)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='order', to='products.Product')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
