# Generated by Django 3.2 on 2022-06-21 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='color',
            field=models.CharField(blank=True, default='', max_length=240, null=True),
        ),
    ]
