# Generated by Django 3.2 on 2022-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitems_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ds', 'دریافت سفارش'), ('am', 'آماده سازی'), ('de', 'درحال ارسال'), ('tp', 'تحویل به پست')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('p', 'payed'), ('r', 'refund')], default='ds', max_length=1),
        ),
    ]
