# Generated by Django 3.2 on 2022-06-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, choices=[('ds', 'دریافت سفارش'), ('am', 'آماده سازی'), ('de', 'درحال ارسال'), ('tp', 'تحویل به پست')], default='ds', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('p', 'payed'), ('r', 'refund')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
