# Generated by Django 3.2 on 2022-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
