# Generated by Django 3.2 on 2022-06-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_club_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ('-id',)},
        ),
    ]
