# Generated by Django 3.2 on 2022-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/th/')),
                ('descreption', models.TextField(blank=True, null=True)),
                ('hide', models.BooleanField(default=False)),
                ('price', models.BigIntegerField(default=0)),
                ('company_price', models.BigIntegerField(default=0)),
                ('price_after_discount', models.BigIntegerField(default=0)),
                ('manufacturer_company', models.CharField(blank=True, max_length=120, null=True)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='products', to='products.Category')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
