# Generated by Django 3.2 on 2022-05-19 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('products', '0005_auto_20220519_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='tags.tag'),
            preserve_default=False,
        ),
    ]
