# Generated by Django 3.2 on 2022-06-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hashtag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
