# Generated by Django 3.2 on 2022-04-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title_image',
            field=models.ImageField(blank=True, upload_to='news'),
        ),
    ]
