# Generated by Django 3.2 on 2022-06-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='hashtag',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
